sudo: required
services:
  - docker

before_install:
  - docker build -t ashskywalker10/docker-react -f Dockerfile.dev .

script:
  - docker run ashskywalker10/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-669468975997"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"